apiVersion: v1
kind: Service
metadata:
  name: demo-client-service
  labels:
    app: demo-client
spec:
  type: ClusterIP
  selector:
    app: demo-client
  ports:
    - port: 8181
      targetPort: 8181